// API 1
GET http://localhost:3000/movies/

###

// API 2
POST http://localhost:3000/movies/
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}

###

//API 3
GET http://localhost:3000/movies/77/

###

PUT http://localhost:3000/movies/46/
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}

###
DELETE http://localhost:3000/movies/46/

###

GET http://localhost:3000/directors/

###

GET http://localhost:3000/directors/45/movies/